### ISSUE TITLE
Invalid Access Token

### ISSUE THREAD

**Issue by Amuri-Bonface** [bdhobare/mpesa-android-sdk#2]
Hello,

When trying to pay up, this Token error always pops up. I have registered the app with Safaricom Developer's portal and it is approved. What could be the problem?
Thanks.

**Comment by Amuri-Bonface** [comment]
I've sorted it out, i was implementing a Production App with test(SandBox) credentials.

Thanks again.

**Comment by bdhobare** [comment]
Thanks @Amuri-Bonface
